server:
  port: 9193
  servlet:
    session:
      tracking-modes: cookie
    context-path: /
#spring
spring:
  application:
    name: cloud-ip-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.9.104.20:8848
      config:
        server-addr: 192.9.104.20:8848  #配置中心地址
        file-extension: yaml  #yaml格式配置文件
    sentinel:
      transport:
        # sentinel dashboard 地址
        dashboard: 192.9.104.20:8018
        # 默认为8719，如果被占用会自动+1，直到找到为止
        port: 8719
  devtools:
    restart:
      enabled: false
  redis:
    database: 3
    host: 192.9.104.243
    port: 6379
    password: 123456
    timeout: 1000
    jedis:
      pool:
        max-active: 200
        max-idle: 10
        max-wait: -1
        min-idle: 0


logging:
  level:
    root:
      debug

management:
  endpoints:
    web:
      exposure:
        include: "*"

###################################### 自定义配置  #################################################
tdt:
  file-properties:
    region-csv: /opt/ip-service/data/global_region.csv   # csv  文件位置 生成 ip2region.db文件使用 下载地址 https://github.com/lionsoul2014/ip2region/tree/master/data
    ip-txt: /opt/ip-service/data/ip.merge.txt      # txt 文件位置 同上  下载地址 https://github.com/lionsoul2014/ip2region/tree/master/data
    region-db: /opt/ip-service/data/ip2region.db   # db 文件位置 ip查询时使用 下载地址 https://github.com/lionsoul2014/ip2region/tree/master/data
    admin-data-csv: /opt/ip-service/data/AdminData.csv # admin data csv
  search-properties:
    type: B-tree      # 数据查询方式 B-tree   Binary   Memory   默认 B-tree
  redis-properties:
    expire-time: 3600 # redis过期时间 单位 秒
  service-url:
    administrative-service: http://cloud-api-administrative-service/api
    