spring:
  devtools:
    restart:
      enabled: false
  redis:
    database: 3
    host: 192.9.104.243
    port: 6379
    password: 123456
    timeout: 1000
    jedis:
      pool:
        max-active: 200
        max-idle: 10
        max-wait: -1
        min-idle: 0






###################################### 自定义配置  #################################################
tdt:
  file-properties:
    region-csv: /opt/ip-service/data/global_region.csv   # csv  文件位置 生成 ip2region.db文件使用 下载地址 https://github.com/lionsoul2014/ip2region/tree/master/data
    ip-txt: /opt/ip-service/data/ip.merge.txt      # txt 文件位置 同上  下载地址 https://github.com/lionsoul2014/ip2region/tree/master/data
    region-db: /opt/ip-service/data/ip2region.db   # db 文件位置 ip查询时使用 下载地址 https://github.com/lionsoul2014/ip2region/tree/master/data
    admin-data-csv: /opt/ip-service/data/AdminData.csv # admin data csv
  search-properties:
    type: B-tree      # 数据查询方式 B-tree   Binary   Memory   默认 B-tree
  redis-properties:
    expire-time: 3600 # redis过期时间 单位 秒
  service-url:
    administrative-service: http://cloud-api-administrative-service/api
    